/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApplicationDtoPost {
  CandidatId?: string ;
  Cv?: File | null;
  JobOfferId?: string;
}
