/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApplicationDtoPost {
  candidatId?: string;
  cv?: string | null;
  jobOfferId?: string;
}
