/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Competence } from '../models/competence';
export interface CandidatDto {
  competences?: Array<Competence> | null;
  cv?: string | null;
  email?: string | null;
  firstname?: string | null;
  id?: string;
  lastname?: string | null;
  telephone?: string | null;
}
