/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

// employee.model.ts
export interface EmployeDTO {
  id: string;
  firstname: string;
  lastname: string;
  email: string;
  telephone: string;
  poste: string;
  
  // Performance fields
  performance?: {
    attendance?: {
      presentDays: number;
      absentDays: number;
      lateDays: number;
      monthlyTrend: number[];
    };
    tasks?: {
      completedOnTime: number;
      completedLate: number;
      notCompleted: number;
      qualityRating: number;
    };
    productivity?: {
      currentScore: number;
      teamAverage: number;
      lastQuarterAverage: number;
    };
    skills?: {
      technical: number;
      communication: number;
      problemSolving: number;
    };
  };
}
