/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Competence } from '../models/competence';
export interface JobOfferDtoCreate {
  id: string ;
  competences?: Array<Competence> | null;
  description?: string | null;
  experience?: number;
  location?: string | null;
  salary?: number;
  title?: string | null;
}
