/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApplicationDtoPost } from '../../models/application-dto-post';

export interface ApiApplicationApplyPost$Params {
      body?: ApplicationDtoPost
}

export function apiApplicationApplyPost(http: HttpClient, rootUrl: string, params?: ApiApplicationApplyPost$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, apiApplicationApplyPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }
  rb.header('Authorization', `Bearer ${localStorage.getItem('token')}`);

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

apiApplicationApplyPost.PATH = '/api/Application/apply';
