/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';
import { TokenService } from '../../services/token.service';
import { CandidatDto } from '../../models/candidat-dto';

export interface ApiCandidatManagementGet$Plain$Params {
}

export function apiCandidatManagementGet$Plain(http: HttpClient, rootUrl: string, params?: ApiCandidatManagementGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CandidatDto>>> {
  const tokenService = new TokenService();
  const rb = new RequestBuilder(rootUrl, apiCandidatManagementGet$Plain.PATH, 'get');
  if (params) {
  }

  rb.header('Authorization', `Bearer ${tokenService.token}`);

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CandidatDto>>;
    })
  );
}

apiCandidatManagementGet$Plain.PATH = '/api/CandidatManagement';
