/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiEmployeManagementGet } from '../fn/employe-management/api-employe-management-get';
import { ApiEmployeManagementGet$Params } from '../fn/employe-management/api-employe-management-get';
import { apiEmployeManagementIdDelete } from '../fn/employe-management/api-employe-management-id-delete';
import { ApiEmployeManagementIdDelete$Params } from '../fn/employe-management/api-employe-management-id-delete';
import { apiEmployeManagementIdGet } from '../fn/employe-management/api-employe-management-id-get';
import { ApiEmployeManagementIdGet$Params } from '../fn/employe-management/api-employe-management-id-get';
import { apiEmployeManagementIdPut } from '../fn/employe-management/api-employe-management-id-put';
import { ApiEmployeManagementIdPut$Params } from '../fn/employe-management/api-employe-management-id-put';
import { EmployeDto } from '../models/employe-dto';

@Injectable({ providedIn: 'root' })
export class EmployeManagementService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiEmployeManagementGet()` */
  static readonly ApiEmployeManagementGetPath = '/api/EmployeManagement';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEmployeManagementGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmployeManagementGet$Response(params?: ApiEmployeManagementGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EmployeDto>>> {
    return apiEmployeManagementGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEmployeManagementGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmployeManagementGet(params?: ApiEmployeManagementGet$Params, context?: HttpContext): Observable<Array<EmployeDto>> {
    return this.apiEmployeManagementGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<EmployeDto>>): Array<EmployeDto> => r.body)
    );
  }

  /** Path part for operation `apiEmployeManagementIdGet()` */
  static readonly ApiEmployeManagementIdGetPath = '/api/EmployeManagement/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEmployeManagementIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmployeManagementIdGet$Response(params: ApiEmployeManagementIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<EmployeDto>> {
    return apiEmployeManagementIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEmployeManagementIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmployeManagementIdGet(params: ApiEmployeManagementIdGet$Params, context?: HttpContext): Observable<EmployeDto> {
    return this.apiEmployeManagementIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<EmployeDto>): EmployeDto => r.body)
    );
  }

  /** Path part for operation `apiEmployeManagementIdPut()` */
  static readonly ApiEmployeManagementIdPutPath = '/api/EmployeManagement/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEmployeManagementIdPut()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  apiEmployeManagementIdPut$Response(params: ApiEmployeManagementIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<EmployeDto>> {
    return apiEmployeManagementIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEmployeManagementIdPut$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  apiEmployeManagementIdPut(params: ApiEmployeManagementIdPut$Params, context?: HttpContext): Observable<EmployeDto> {
    return this.apiEmployeManagementIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<EmployeDto>): EmployeDto => r.body)
    );
  }

  /** Path part for operation `apiEmployeManagementIdDelete()` */
  static readonly ApiEmployeManagementIdDeletePath = '/api/EmployeManagement/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEmployeManagementIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmployeManagementIdDelete$Response(params: ApiEmployeManagementIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return apiEmployeManagementIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEmployeManagementIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmployeManagementIdDelete(params: ApiEmployeManagementIdDelete$Params, context?: HttpContext): Observable<string> {
    return this.apiEmployeManagementIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

}
