/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiJobOfferCreatePost } from '../fn/job-offer/api-job-offer-create-post';
import { ApiJobOfferCreatePost$Params } from '../fn/job-offer/api-job-offer-create-post';

@Injectable({ providedIn: 'root' })
export class JobOfferService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiJobOfferCreatePost()` */
  static readonly ApiJobOfferCreatePostPath = '/api/JobOffer/create';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiJobOfferCreatePost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiJobOfferCreatePost$Response(params?: ApiJobOfferCreatePost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiJobOfferCreatePost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiJobOfferCreatePost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiJobOfferCreatePost(params?: ApiJobOfferCreatePost$Params, context?: HttpContext): Observable<void> {
    return this.apiJobOfferCreatePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
